@URL=https://api.drewferrie.co.uk/

POST {{URL}} HTTP/1.1
Content-Type: application/json
Accept: "application/json"

{
    "sourceLang": "en",
    "targetLang": "es",
    "sourceText": "walk"
}

###

GET {{URL}} HTTP/1.1
Content-Type: application/json
Accept: "application/json"
